// Code generated by mockery v2.53.5. DO NOT EDIT.

package repository

import (
	context "context"
	models "kingzecole/pay-by-bank-service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateMandate provides a mock function with given fields: ctx, v
func (_m *MockRepository) CreateMandate(ctx context.Context, v *models.Mandate) error {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for CreateMandate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Mandate) error); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateMandate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMandate'
type MockRepository_CreateMandate_Call struct {
	*mock.Call
}

// CreateMandate is a helper method to define mock.On call
//   - ctx context.Context
//   - v *models.Mandate
func (_e *MockRepository_Expecter) CreateMandate(ctx interface{}, v interface{}) *MockRepository_CreateMandate_Call {
	return &MockRepository_CreateMandate_Call{Call: _e.mock.On("CreateMandate", ctx, v)}
}

func (_c *MockRepository_CreateMandate_Call) Run(run func(ctx context.Context, v *models.Mandate)) *MockRepository_CreateMandate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Mandate))
	})
	return _c
}

func (_c *MockRepository_CreateMandate_Call) Return(_a0 error) *MockRepository_CreateMandate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateMandate_Call) RunAndReturn(run func(context.Context, *models.Mandate) error) *MockRepository_CreateMandate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
